"""Vivino coverage gap report for build_reference_data.py (maintainer tool).

Reads Vivino's reference lists and reports what our bundled seed does NOT cover,
so a maintainer can decide what to curate. No Vivino data is written into the
shipped reference_data.py - this only measures coverage.

`compute_gaps` is pure (no network) and unit-tested; the fetchers do the I/O.
"""
from __future__ import annotations

from collections import defaultdict

VIVINO_HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                   "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate",  # no 'br': requests has no brotli decoder
    "Referer": "https://www.vivino.com/",
}


def compute_gaps(vivino_grapes, vivino_regions, bundle_countries, bundle_regions,
                 bundle_grapes, normalize):
    """Pure diff. Returns dict of missing grapes/regions/countries + stats.

    vivino_grapes: [name, ...]
    vivino_regions: [{'name':.., 'country_code':..}, ...]
    bundle_*: lists of dicts with 'name'/'code'/'country_code'/'aliases'.
    """
    grape_norms = set()
    for g in bundle_grapes:
        grape_norms.add(normalize(g["name"]))
        grape_norms.update(normalize(a) for a in g.get("aliases", []))

    country_codes = {c["code"].upper() for c in bundle_countries}

    region_index = defaultdict(set)
    for r in bundle_regions:
        cc = (r["country_code"] or "").upper()
        region_index[cc].add(normalize(r["name"]))
        region_index[cc].update(normalize(a) for a in r.get("aliases", []))

    missing_grapes = sorted({g for g in vivino_grapes if normalize(g) not in grape_norms})

    missing_regions = defaultdict(list)
    vivino_ccs = set()
    for reg in vivino_regions:
        cc = (reg.get("country_code") or "").upper()
        if cc:
            vivino_ccs.add(cc)
        if normalize(reg.get("name", "")) not in region_index.get(cc, set()):
            missing_regions[cc].append(reg.get("name", ""))

    missing_countries = sorted(vivino_ccs - country_codes)

    grapes_total = len({normalize(g) for g in vivino_grapes})
    return {
        "missing_grapes": missing_grapes,
        "missing_regions": {k: sorted(v) for k, v in missing_regions.items()},
        "missing_countries": missing_countries,
        "stats": {
            "grapes_total": grapes_total,
            "grapes_matched": grapes_total - len(missing_grapes),
            "regions_total": len(vivino_regions),
            "regions_missing": sum(len(v) for v in missing_regions.values()),
            "countries_missing": len(missing_countries),
        },
    }


# ── Network (not unit-tested; mocked in tests) ───────────────────────────────

def _session():
    import requests
    s = requests.Session()
    s.headers.update(VIVINO_HEADERS)
    try:
        s.get("https://www.vivino.com/", timeout=15)
    except Exception:
        pass
    return s


def fetch_vivino_grapes(session):
    r = session.get("https://www.vivino.com/api/grapes",
                    headers={"Accept": "application/json"}, timeout=30)
    r.raise_for_status()
    data = r.json()
    lst = data if isinstance(data, list) else data.get("grapes", [])
    return [g.get("name") for g in lst if isinstance(g, dict) and g.get("name")]


def fetch_vivino_regions(session):
    r = session.get("https://www.vivino.com/api/regions",
                    headers={"Accept": "application/json"}, timeout=60)
    r.raise_for_status()
    data = r.json()
    lst = data if isinstance(data, list) else data.get("regions", [])
    out = []
    for reg in lst:
        c = reg.get("country")
        code = (c.get("code") if isinstance(c, dict) else c) or ""
        out.append({"name": reg.get("name", ""), "country_code": str(code).upper()})
    return out


def _render_markdown(gaps):
    s = gaps["stats"]
    lines = [
        "# Vivino coverage gap report",
        "",
        "Generated by `scripts/build_reference_data.py --vivino-report`. This is a",
        "coverage measurement only - no Vivino data is bundled into the app.",
        "",
        "## Summary",
        f"- Grapes: {s['grapes_matched']}/{s['grapes_total']} matched, "
        f"**{len(gaps['missing_grapes'])} missing**",
        f"- Regions: **{s['regions_missing']}** of {s['regions_total']} unmatched "
        f"(across {len(gaps['missing_regions'])} countries)",
        f"- Countries: **{s['countries_missing']}** Vivino country codes not in the bundle",
        "",
        "## Missing grapes (curation candidates)",
    ]
    lines += [f"- {g}" for g in gaps["missing_grapes"]] or ["- (none)"]
    lines += ["", "## Missing countries", ]
    lines += [f"- {c}" for c in gaps["missing_countries"]] or ["- (none)"]
    lines += ["", "## Missing regions by country (counts + examples)"]
    for cc in sorted(gaps["missing_regions"], key=lambda k: -len(gaps["missing_regions"][k])):
        names = gaps["missing_regions"][cc]
        examples = ", ".join(names[:8]) + (" ..." if len(names) > 8 else "")
        lines.append(f"- **{cc or '??'}**: {len(names)} - {examples}")
    return "\n".join(lines) + "\n"


def write_gap_report(bundle_countries, curated_regions, curated_grapes, path, normalize):
    """Fetch Vivino lists, diff against the bundle, write a markdown report."""
    bundle_regions = [{"name": n, "country_code": cc, "aliases": al}
                      for (n, cc, lat, lon, al) in curated_regions]
    bundle_grapes = [{"name": n, "aliases": al} for (n, color, al) in curated_grapes]

    print("Fetching Vivino reference lists (rate-limited; may take a moment)...")
    s = _session()
    vivino_grapes = fetch_vivino_grapes(s)
    vivino_regions = fetch_vivino_regions(s)
    gaps = compute_gaps(vivino_grapes, vivino_regions, bundle_countries,
                        bundle_regions, bundle_grapes, normalize)
    with open(path, "w", encoding="utf-8") as f:
        f.write(_render_markdown(gaps))
    print(f"Wrote gap report: {path}")
    print(f"  grapes missing: {len(gaps['missing_grapes'])}, "
          f"regions missing: {gaps['stats']['regions_missing']}, "
          f"countries missing: {gaps['stats']['countries_missing']}")
    return gaps
